### ISSUE TITLE
Build & Release multiple modules or each plugin as binaries

### ISSUE THREAD

**Issue by t-kikuc** [t-kikuc/pipecd-plugin-prototypes#3]
I want to fetch plugins from remote instead of local.

i.e.

```yaml
apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  plugins:
    - name: ECSPRESSO
      # url: file:///<HOME>/.piped/plugins/ecspresso  # Local
      url:  github.com/t-kikuc/pipecd-plugin-prototypes/releases/ecspresso:vX.Y.Z # Remote

```
